# Generated by Django 5.2.7 on 2025-10-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('weapons', models.CharField(max_length=150)),
                ('year', models.IntegerField(max_length=150)),
                ('leader', models.CharField(max_length=150)),
                ('details', models.CharField(max_length=300)),
            ],
        ),
    ]
