# Generated by Django 5.2.7 on 2025-10-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='army',
            name='year',
            field=models.IntegerField(),
        ),
    ]
