# Generated by Django 5.2.7 on 2025-10-20 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_army_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=150)),
                ('enemy', models.CharField(max_length=150)),
                ('losses', models.IntegerField()),
                ('enemy_losses', models.IntegerField()),
                ('outcome', models.CharField(choices=[('W', 'Victory'), ('L', 'Defeat'), ('D', 'Draw')], default='W', max_length=1)),
                ('discussion', models.CharField(max_length=250)),
                ('army', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.army')),
            ],
        ),
    ]
