# Generated by Django 5.2.7 on 2025-10-20 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_battle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='battle',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='army',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='battle',
            name='date',
            field=models.DateField(verbose_name='Final day of the battle or siege'),
        ),
    ]
